services:

  api:
    image: image_api_rest  # Aquí puedes especificar el nombre de la imagen
    restart: always
    build: ./api
    volumes:
     - ./api:/usr/src/app
    ports:
     - 5000:3000
    networks:
     - app-tier
    container_name: container_ api_rest

networks:
  app-tier:
    driver: bridge     
volumes:
  database-data: